name: "exploit_kernel"
repository: github.com/minhlongmt183/thesis-plugin-research/trivy-plugin-exploit-kernel
version: "0.0.14"
usage: scan linux kernel and auto exploit
description: |-
  A Trivy plugin that scans the kernel to exploit get root based CVE
  Usage: trivy exploit TYPE[.VERSION][.GROUP] NAME
platforms:
#  - selector: # optional
#      os: darwin
#      arch: amd64
#    uri: ./trivy-kubectl # where the execution file is (local file, http, git, etc.)
#    bin: ./trivy-kubectl # path to the execution file
  - selector: # optional
      os: linux
      arch: amd64
    uri: https://github.com/liamg/traitor/releases/download/v0.0.14/traitor-amd64
    bin: ./traitor-amd64
  - selector:
      os: darwin
      arch: arm64
    uri: ./traitor-amd64
    bin: ./traitor-amd64